[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 15 }

[profile.lite]
optimizer = false
via_ir = false
verbosity = 1

[profile.debug]
debug = true
optimizer = false
via_ir = false
verbosity = 2

[profile.optimized]
optimizer = true
optimizer_runs = 1000000
via_ir = true

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
